#!/bin/bash

_PLATFORM=`uname -sm`
PLATFORM=${_PLATFORM/ /-}

WRAPPER_URL="https://raw.githubusercontent.com/osheroff/onetimeserver/master/wrapper/wrapper.c"
ONETIMESERVER_URL="https://raw.githubusercontent.com/osheroff/onetimeserver/master/wrapper/wrapper.c"
CACHE_DIR=$HOME/.onetimeserver/$PLATFORM

function usage() {
  echo "usage: onetimeserver [--mysql-version=VERSION|-m VERSION] [-v|--verbose] [mysql_args...]"
}

while [[ $# > 0 ]]
do
  case $1 in
    --mysql-version=*)
      MYSQL_VERSION="-mysql-version ${i#*=}"
      ;;
    -m)
      shift
      MYSQL_VERSION="-mysql-version $1"
      ;;
    -d|--debug)
      DEBUG="-debug"
      ;;
    -h|--help)
      usage
      exit
      ;;
    *)
      EXTRA_ARGS="$EXTRA_ARGS $1"
      ;;
  esac
  shift

done

mkdir -p $CACHE_DIR


if [ "$1" == "clear" ] ; then
  rm -Rf $CACHE_DIR/*
  exit 0
fi

cd $CACHE_DIR

if ! [ -f $CACHE_DIR/wrapper ]
then
  curl -s "$WRAPPER_URL" > $CACHE_DIR/wrapper.c
  gcc -g -O2 $CACHE_DIR/wrapper.c -o $CACHE_DIR/wrapper
fi

if ! [ -f $CACHE_DIR/onetimeserver-go ]
then
  curl -s $ONETIMESERVER_URL > $CACHE_DIR/onetimeserver-go
fi

exec $CACHE_DIR/wrapper $MYSQL_VERSION -ppid $PPID -type mysql -- $EXTRA_ARGS
